In [84]:
items = [1,2,3,4,5]
squared = (lambda z:z**2,items)
squared

(<function __main__.<lambda>(z)>, [1, 2, 3, 4, 5])

In [15]:
class vehicle:
    wheels = 2
    maxspeed = 100
car = vehicle()
motorbike = vehicle()
bike = vehicle()

car.wheels,car.maxspeed

(2, 100)

In [25]:
def ans(z):
 return(z*4)
ans(4)

16

In [42]:
ans = (lambda z:z*4)
ans(4)

16

In [53]:
class HRBusinessunit:
   org_name = "ABC Inc."
   def emp_details(name,id):
    print("Name of employee is",name, "and employee id is" ,id)
    
emp1 = HRBusinessunit    
emp1.emp_details('john','30')

Name of employee is john and employee id is 30


In [57]:
class HRBusinessunit:
   def __init__(self,name,id):
    print("Name of employee is",name, "and employee id is" ,id)
HRBusinessunit('john','30')

Name of employee is john and employee id is 30


In [60]:
class Edureka():
    def Hello(self):
        print("Happy Learning")
#made an object with class edureka
ob = Edureka()
ob.Hello()

Happy Learning


In [63]:
#Global and Local variables
a=50
class Edureka():
    b=60
    a=a
    print('inside class:',a,b)
  

inside class: 50 60


In [65]:
class Example():
    def __init__(self):
        self.__pri="Private Attribute"
        self._pro="Protected Attribute"
        self.pub="Public Attribute"

In [68]:
ob= Example()
print(ob._pro)
print(ob.pub)
#print(ob.__pri) throws error

Protected Attribute
Public Attribute


In [81]:
#private and publicmethods
class myclass:
    def mypublicmethod():
        print("public method")
    def __myprivatemethod(self):
        print("private method")
obj=myclass
obj.mypublicmethod()

#obj.__myprivatemethod() throw error  

public method


In [85]:
class Employee:
    #initializing
    def __init__(self):
        print("employee created")
    def __del__(self):
        print("destructor called")
obj = Employee()
del obj
   

employee created
destructor called


In [88]:
#Date data types
from datetime import datetime
datetime.now()

datetime.datetime(2021, 2, 12, 0, 34, 54, 941109)

In [96]:
DOB = datetime(1989,8,27)
DOB_formatted = datetime.strftime(DOB,'%d-%m-%y')
print(DOB_formatted)

27-08-89


In [110]:
from random import*
for i in range(0,10):
    print(randint(0,9))

8
3
6
6
4
5
3
6
4
8


In [113]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [122]:
a = 1000
b = 1000
print(id(a))
print(id(b))

140298205837776
140298205837936


In [146]:
a = "edureka"
a[5:1:-2]

'kr'

In [152]:
ages = ['rahul',105.5, True, 10, 20]
len(ages)
ages.append([30, 40, 50])
ages

['rahul', 105.5, True, 10, 20, [30, 40, 50]]

In [154]:
ages =(4,5,6)
print(id(ages))

140298205204224


In [161]:
list1 = list(ages)
list1[0] = 40
ages = tuple(list1)
ages
print(id(ages))

140298204689408


In [171]:
stu_details = {'sid': [1,2,3,4,5],'s_name': ['a','b','c','d','e'],'Region': ['south','East','East','North','west']}

In [172]:
dict1 = {'a':1, 'b':2}
dict2 = {'a':10, 'c':3}
dict1.update(dict2)

In [173]:
dict1

{'a': 10, 'b': 2, 'c': 3}

In [175]:
type(stu_details)

dict

In [ ]:
#sets

In [187]:
set1 = {1,1,2,3,4,5,6,6,7,8,9,10}
type(set1)
set1

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [185]:
set1.add(11)
set1

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

In [189]:
set1.discard(10)
set1

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [193]:
set1
set1.remove(8)

In [196]:
set1.update([8,9,10])
set1

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [203]:
set1 = {1,2,3,4,5}
set2 = {4,5,6}
set3 = {3,4,5}
set4 = {6,7,8}

In [201]:
set1.isdisjoint(set2)


False

In [199]:
set1.difference(set2)

{1, 2, 3}

In [202]:
#.difference_update
#.symmetric_difference
#.symmetric_difference_update
#.union
#.update
#.intersection
#.intersection_update
#.issuperset
#.isubset

In [206]:
list(range(0,10))
list(range(20,1,-2))
type(range(0,5))

range

In [207]:
a = None
type(a)

NoneType

In [ ]:
set1

In [ ]:
#operators
 #Arithmetic
 #relational /comparision
 #logical
 #equality
 #Assignment
 #ternary
 #special   

In [210]:
x = 30 if 10>20 else 40
x

40

In [212]:
a = 7
b = 4
c = 5
a if a>b>c else b if b>c else c

5

In [219]:
a = 7
b = 4
c = 5
x = a if a>=b and a>=c else b if b>c else c
x

7

In [224]:
#compound Assignment
x = 100
x += 20
x
x -=40
x

80

In [225]:
#special operators

 #Identity
    #is
    #is not
  #Membership
    #in
    #not in
    

In [226]:
a = 10
b = 10
a is b

True

In [231]:
a = 257
b = 257
a is b

False

In [1]:
age = input('enter the age')
age

enter the age23


'23'

In [2]:
a = int(input('enter the num'))
b = int(input('enter the num'))
a+b


enter the num2
enter the num3


5

In [13]:
def greeting(name='Guest'):
    '''This function is helping to greet the audience'''
    print('Good Morning',name)
greeting('Sindhu')
greeting()

Good Morning Sindhu
Good Morning Guest


In [1]:
a = 10
b = 20
c = 30
print(a,b,c,sep='%')

10%20%30


In [2]:
print('Hello',end=' ')
print('students',end=' ')
print('to learn python',end=' ')
print('you have to practice',end=' ')


Hello students to learn python you have to practice 

In [6]:
name = 'Rahul'
salary = 10000
company = 'Deloitte'
print('Hello {}, your salary is {} and your company is {}'.format(name,salary,company))


Hello Rahul, your salary is 10000 and your company is Deloitte


In [8]:
#fibonacci series
num = int(input('how many terms'))
no_1 = 0
no_2 = 1
count = 0
if num <= 0:
    print('please enter only positive numbers')
elif num == 1:
    print(no_1)
else:
    while count < num:
        print(no_1,end = ' ')
        nth = no_1 + no_2
        no_1 = no_2
        no_2 = nth
        count += 1       

how many terms10
0 1 1 2 3 5 8 13 21 34 

In [22]:
N = int(input('please enter the integer'))
sum = 0
while N:
    sum = sum + (N%10)
    N = N//10
print(sum) 

please enter the integer1510
7


In [ ]:
N=int(input())
numlist=[]
for i in range(N):
    numlist.append(int(input()))
print(numlist)

In [31]:
N=input()
s=0
for i in list(N):
    s=s+int(i)**3
if s==int(N):
    print('Yes')
else:
    print('No')


200
No


In [ ]:
#If else Conditions
if marks < 40:
    output
else:
    output

In [33]:
marks = int(input('enter your marks: '))
if marks<40:
    print('you failed the exam')
else:
    print('you passed the exam')

enter your marks: 35
you failed the exam


In [36]:
marks = int(input('enter your marks: '))
if marks<40:
    print('your grade is E')
elif marks>=40 and marks<=50:
    print('your grade is D')
elif marks>=50 and marks<=60:
    print('your grade is C')
elif marks>=60 and marks<=70:
    print('your grade is B')
elif marks>=70 and marks<=80:
    print('your grade is A')
else:
    print('your grade is A+')
    

enter your marks: 85
your grade is A+


In [37]:
x = int(input('enter the number: '))
y = int(input('enter the number: '))
if x>y:
    print(x, 'is the bigger number')
else:
    print(y, 'is the bigger number')
    

enter the number: 21
enter the number: 10
21 is the bigger number


In [40]:
x = int(input('enter the number: '))
if x%2==0:
    print(x, 'is an even number')
else:
    print(x, 'is an odd number')


enter the number: 500
500 is an even number


In [55]:
num = int(input("Enter a number: "))
if num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
        else:
            print(num, "is a prime number")
else:
    print(num, "is not a prime number")

Enter a number: 13
13 is a prime number
13 is a prime number
13 is a prime number
13 is a prime number
13 is a prime number
13 is a prime number
13 is a prime number
13 is a prime number
13 is a prime number
13 is a prime number
13 is a prime number


In [50]:
# for loops for iterations
import time
s = 'EDUREKA'
for i in s:
    print(i)
    time.sleep(1)
print('hi')

E
D
U
R
E
K
A
hi


In [53]:
sales = [4344,3343,4444,5564,7788,9878,4567,3456,9567,5432]
for i in sales:
    print(i)
    time.sleep(1)

4344
3343
4444
5564
7788
9878
4567
3456
9567
5432


In [56]:
sales = [4344,3343,4444,5564,7788,9878,4567,3456,9567,4444]
for i in range(0,len(sales)):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [57]:
sales = [4344,3343,4444,5564,7788,9878,4567,3456,9567,4444]
for i in sales:
    print(sales.index(i))

0
1
2
3
4
5
6
7
8
2


In [58]:
sales = [4344,3343,4444,5564,7788,9878,4567,3456,9567,4444]
for i in range(0,len(sales)):
    print(i, ':', sales[i])

0 : 4344
1 : 3343
2 : 4444
3 : 5564
4 : 7788
5 : 9878
6 : 4567
7 : 3456
8 : 9567
9 : 4444


In [59]:
sales = [4344,3343,4444,5564,7788,9878,4567,3456,9567,4444]
for (i,s) in zip (range(0,len(sales)),sales):
    print(i, ':', s)

0 : 4344
1 : 3343
2 : 4444
3 : 5564
4 : 7788
5 : 9878
6 : 4567
7 : 3456
8 : 9567
9 : 4444


In [64]:
sales = [3545,3333,4545,2222]
profit = [453,222,323,344]
profitratio = []
for i in range(0,len(sales)): # or range(len(sales)-1,-1,-1)
    profitratio.append(profit[i]/sales[i])
profitratio

[0.12778561354019746,
 0.0666066606660666,
 0.07106710671067107,
 0.1548154815481548]

In [65]:
#while
coupouns = 5
utilized = 0
while utilized<=5:
    print('Total coupouns left are: ',coupouns-utilized)
    utilized = utilized+1
print('No coupouns left')

Total coupouns left are:  5
Total coupouns left are:  4
Total coupouns left are:  3
Total coupouns left are:  2
Total coupouns left are:  1
Total coupouns left are:  0
No coupouns left


In [ ]:
while False:
    print('Hi')

In [75]:
a = input('insert some values: ')
a

insert some values: 10


'10'

In [74]:
a = [int(i) for i in input('insert some values: ').split()]
a

insert some values: 10 20 30 40 50


[10, 20, 30, 40, 50]

In [78]:
a = [eval(i) for i in input('insert some values: ').split()]
a
type(a[2])

insert some values: 10 10.5 True 'Rahul'


bool

In [79]:
#Functions
def greeting():
    print('Good Morning')
greeting()

Good Morning


In [81]:
#import keyword
#keyword.kwlist

In [88]:
def greeting(name='Guest'):
    '''This function is helping to greet the audience'''
    print('Good Morning',name)
greeting('Sindhu')
greeting()

Good Morning Sindhu
Good Morning Guest


In [ ]:
greeting() 

In [90]:
def square(x=10):
    print(x*x)
square()

100


In [97]:
#to print the values
def add(a,b):
    print(a+b)
z = add(10,20)

30


In [98]:
#to store the outputs return function will be used
def add(a,b):
    return(a+b)
z = add(10,20)

In [99]:
z

30

In [102]:
def evenodd(n):
    if n%2==0:
        return 'The number is even'
    else:
        return 'The number is Odd'
a = evenodd(10)

In [103]:
a

'The number is even'

In [108]:
def fact(n):
    result = 1
    while n>=1:
        result = result*n
        n = n-1
    return result
fact(5)

120

In [111]:
n = 5
result = 1
while n>=1:
    result = result*n
    n = n-1
    print(result)

5
20
60
120
120


In [112]:
def calc(a,b):
    add = a+b
    sub = a-b
    mul = a*b
    div = a/b
    return(add)
    return(sub)
    return(mul)
    return(div)
calc(10,2)
only one return value will be returned

12

In [118]:
def calc(a,b):
    add = a+b
    sub = a-b
    mul = a*b
    div = a/b
    return({'add':add, 'sub':sub, 'mul':mul, 'div':div})
    #return[add,sub,mul,div]
    #return(add,sub,mul,div)
a = calc(10,2)

In [119]:
a

{'add': 12, 'sub': 8, 'mul': 20, 'div': 5.0}

In [122]:
# For multiple and large values(variable length arguement)
def add(*args):
    result = 0
    for i in args:
        result = result+i
    print(result)
add(10,20,30,40)

100


In [14]:
# Types of variables in a function
  #Local variable
  #Global Variable
p = 100
def f1():
    #global p#(updates global variable)
    p =20
    print('f1', p)
f1()
def f2():
    print('f2', p)
f2()


f1 20
f2 100


In [126]:
#Lambda Functions

def square(n):
    print(n*n)
square(10)

100


In [135]:
sq1 = lambda n,m : n**m
sq1(10,3)

1000

In [130]:
sum1 = lambda a,b : a+b
sum1(10,20)

30

In [136]:
x = lambda a,b : a if a>b else b 
x(10,20)

20

In [ ]:
filter
map
reduce

In [10]:
len('character')

9

In [19]:
#Filter
#filter(function,list)
list1 = [43,45,44,33,22,33,22,11,12]
def iseven(x):
    if x%2==0:
        return x
    else:
        return None
list(filter(iseven, list1))

[44, 22, 22, 12]

In [29]:
list(filter(lambda x : x%2==0, list1))

[45, 33, 33, 12]

In [24]:
#Map
#map(function, list)
list1 = [43,45,44,33,22,33,22,11,12]
def double(x):
    return 2*x
list(map(double,list1))

[86, 90, 88, 66, 44, 66, 44, 22, 24]

In [28]:
list1 = [43,45,44,33,22,33,22,11,12]
list(map(lambda x : x*.01, list1))

[0.43, 0.45, 0.44, 0.33, 0.22, 0.33, 0.22, 0.11, 0.12]

In [30]:
list1 = [1,2,3,4,5]
list2 = [5,4,3,2,1]
list(map(lambda x,y : x*y, list1,list2))

[5, 8, 9, 8, 5]

In [33]:
#reduce
#reduce(function,list)
from functools import reduce
list1 = [43,45,44,33,22,33,22,11,12]
reduce(lambda x,y : x+y, list1)

265

In [35]:
list1 = [1,2,3,4,5]
def multiple(x,y):
    return x*y
reduce(multiple, list1)

120

In [34]:
import functools as f
f.#tab will get all the functions

<module 'functools' from '/Users/abhisheksuhas/opt/anaconda3/lib/python3.8/functools.py'>

In [39]:
#string operations
#strip#lstrip#rstrip
city = input('enter the city name: ')
list1 = ['gurgaon','Delhi','Hyderabad','Bengaluru','Chennai','Hyderabad']
if city.strip(' ').strip('$') in list1:
    print('your city is available')
else:
    print('your city is not available')

enter the city name:   Delhi
your city is available


In [53]:
#find,reverse find,
s = 'sindhugurajalasindhugurajala'
print(s.find('s',5,20))#between index 5 and 20
print(s.rfind('r'))
print(s.find('b'))#if no value it returns -1

14
22
-1


In [ ]:
s = 'sindhugurajalasindhugurajala'

In [64]:
s = 'sindhuisindhui'
f = 'd'
flag = False
pos = -1
n = len(s)
while True:
    pos = s.find(f,pos+1,n)
    if pos==-1:
        break
    print('Found at index: ', pos)
    flag = True
if flag==False:
    print('Not Found')

Found at index:  3
Found at index:  10


In [75]:
s = 'sindhuisindhuisindhu'
print(s.count('sindhu'))
print(s.count('sindhu',13,20))
len(s)

3
1


20

In [77]:
s = 'sindhuisindhuisindhu'
print(s.replace('sindhu','abhi'))

abhiiabhiiabhi


In [79]:
s = 'sindhugsindhugsindhu'
s.split('g')


['sindhu', 'sindhu', 'sindhu']

In [80]:
s = 'sindhu-gurajala-edureka-data-science-python'
s.split('-',3)

['sindhu', 'gurajala', 'edureka', 'data-science-python']

In [82]:
s = ['sindhu', 'sindhu', 'sindhu']
'$'.join(s)


'sindhu$sindhu$sindhu'

In [83]:
s = 'sindhu gurajala is a data scientist'
print(s.upper())
print(s.lower())
print(s.title())
print(s.swapcase())
print(s.capitalize())

SINDHU GURAJALA IS A DATA SCIENTIST
sindhu gurajala is a data scientist
Sindhu Gurajala Is A Data Scientist
SINDHU GURAJALA IS A DATA SCIENTIST
Sindhu gurajala is a data scientist


In [85]:
print(s.startswith('sindhu'))
print(s.endswith('on'))

True
False


In [89]:
print('sindhu'.isalnum())
print('sindhu'.isalpha())
print('sindhu'.isdigit())
print('sindhu123'.isalnum())
print('sindhu123'.isalpha())
print('sindhu123'.isdigit())
print('sindhu'.islower())
print('sindhu'.isupper())
print('Sindhu'.istitle())
print('sindhu gurajala'.isspace())
print('   '.isspace())

True
True
False
True
False
False
True
False
True
False
True


In [91]:
s = 'edureka'
i = len(s)-1
output = ''
while i>=0:
    output = output+s[i]
    i = i -1
print(output)

akerude


In [349]:
s = 'edureka'
print('the charcaters at even index is: ',s[::2])
print('the characters at odd index is: ',s[1::2])

the charcaters at even index is:  euea
the characters at odd index is:  drk


In [350]:
s = 'edureka'
x = len(s)
i=0
while i<x:
    print('the charcaters at even index is: ',s[i])
    i = i+2
i=1
while i<x:
    print('the characters at odd index is: ',s[i])
    i = i+2

the charcaters at even index is:  e
the charcaters at even index is:  u
the charcaters at even index is:  e
the charcaters at even index is:  a
the characters at odd index is:  d
the characters at odd index is:  r
the characters at odd index is:  k


In [221]:
#input = s1=john,s2=jame 
#output = jjoahmne
s1 = 'john'
s2 = 'jame'
s = ' '
for i in range(len(s1)):
    s += s1[i]+s2[i]
print(s)

 jjoahmne


In [334]:
#input =a4b3c2
#output = aaaabbbcc
t = 'a4b3c2'
output = ''
for i in t:
    if i.isalpha():
        x = i
    else:
        output = output+x*int(i)
print(output)

aaaabbbcc


In [347]:
#input = B4A1D3
#output = ABD134
text = 'B4A1D3'
a = []
d = []
for ch in text:
    if ch.isalpha():
        a.append(ch)
    else:
        d.append(ch)
output = ''.join(sorted(a)+sorted(d))
print(output)

ABD134


In [114]:
#Regular expressions
import re

In [131]:
#compile
s = 'cdccdccccdccdcdccd'
pattern = re.compile('cd')
matcher = pattern.finditer(s)
for m in matcher:
    print('match is available at the start index : ',m.start(), m.end(), m.group())
print(pattern)


match is available at the start index :  0 2 cd
match is available at the start index :  3 5 cd
match is available at the start index :  8 10 cd
match is available at the start index :  11 13 cd
match is available at the start index :  13 15 cd
match is available at the start index :  16 18 cd
re.compile('cd')


In [135]:
matcher = re.finditer('[abcp]','a4rt56byhjut$ op7cha..b')
for m in matcher:
    print(m.start(),'..',m.end(),'..',m.group())
#not vales inside
matcher = re.finditer('[^abcp]','a4rt56byhjut$ op7cha..b')
for m in matcher:
    print(m.start(),'..',m.end(),'..',m.group())

0 .. 1 .. a
6 .. 7 .. b
15 .. 16 .. p
17 .. 18 .. c
19 .. 20 .. a
22 .. 23 .. b
1 .. 2 .. 4
2 .. 3 .. r
3 .. 4 .. t
4 .. 5 .. 5
5 .. 6 .. 6
7 .. 8 .. y
8 .. 9 .. h
9 .. 10 .. j
10 .. 11 .. u
11 .. 12 .. t
12 .. 13 .. $
13 .. 14 ..  
14 .. 15 .. o
16 .. 17 .. 7
18 .. 19 .. h
20 .. 21 .. .
21 .. 22 .. .


In [ ]:
#\s-spaces
#\S-except spaces
#\d-digits
#\D-except Digits
#\w-all alpha numerics values
#\W-except alpha numerics
#. -All characters
#[a-z]-all the lower case 
#[A-Z]-all upper case letters
#[0-9]-all numbers
#and for not '[^'

In [138]:
matcher = re.finditer('c','cdccdcccdccccddcd')
for m in matcher:
    print(m.start(),',',m.end(),',',m.group())
#c+ -any number of c or continues,only c together or individual
#C* - any number of c including 'o',
#c? -atleast one c and also if no c..atmost maximum 1 c
#c{3}-atleast 3 c
#c{2,3}-both 2 c and 3 c

0 , 1 , c
2 , 4 , cc
5 , 8 , ccc
9 , 13 , cccc
15 , 16 , c


In [139]:
matcher = re.finditer('^c','cdccdcccdccccddcd')
for m in matcher:
    print(m.start(),',',m.end(),',',m.group())
#^c-sentence or word starting with c
#c$- ending with c

1 , 2 , d
4 , 5 , d
8 , 9 , d
13 , 14 , d
14 , 15 , d
16 , 17 , d


In [ ]:
#finditer
#compile
#match
#fullmatch
#search
#findall
#sub
#subn
#split

In [150]:
s = 'sindhugurajalasindhuanuragsisindhu'
#m = re.match('abhi',s)looks in string from the start
#match always looks from start
#type(m)
m = re.match('sindhu',s)
#type(m)
if m!=None:
    print('match is available')
else:
    print('match is not available')

match is available


In [152]:
s = 'sindhugurajalasindhuanurag'
m = re.fullmatch('sindhugurajalasindhuanurag',s)
#looks for full match in the string
if m!=None:
    print('match is available')
else:
    print('match is not available')

match is available


In [158]:
s = 'cdccdccdccd'
#gives the index position of the first iteration of the character searching
m = re.search('d',s)
if m!=None:
    print(m.start(),',',m.end())

1 , 2


In [164]:
s = input('enter the keyword: ')
m = re.findall(s,'python is easy.python is an amazing programming language.python is the future.python is simple.python is userfriendly.python is basic for AI')
if len(m)>5:
    print('your resume is selected')
else:
    print('your resume is rejected')

enter the keyword: python
your resume is selected


In [166]:
re.findall('[0-9]','trs76ghg')
re.findall('[a-z]','jdag7kgf8nkjhf9')

['j', 'd', 'a', 'g', 'k', 'g', 'f', 'n', 'k', 'j', 'h', 'f']

In [167]:
#substitute-substitute digits with #
re.sub('\d','#','54sindhu67')

'##sindhu##'

In [168]:
#substitutes and returns the number of substitutions happened
re.subn('\d','#','54sindhu67')

('##sindhu##', 4)

In [169]:
#split the characters
re.split('-','10-20-30-40')

['10', '20', '30', '40']

In [171]:
#split with .should be always given in'\.' or [.]
re.split('[.]','www.edureka.co')

['www', 'edureka', 'co']

In [240]:
s = 'learning python is very easy'
res = re.search('^learn',s)
if res!=None:
    print('starting with learn')
else:
    print('not starting with learn')

starting with learn


In [177]:
#ignore the Case sensitive
s = 'learning python is very easy'
res = re.search('Easy$', s,re.IGNORECASE)
if res!=None:
    print('ending with easy')
else:
    print('not ending with easy')

ending with easy


In [ ]:
#New Programming Language - Rython - Identifiers
#1. The allowable characters should
    #a.Alphabets(a-z,A-Z)
    #b.digits(0-9)
    #c. # 
#2. first character should be lower a-k
#3. second character should be divisible by 3 =[0,3,6,9]

In [ ]:
a3# - valid
a4# - Invalid
t3# - Invalid
a3_ - Invalid

In [182]:
s = input('enter the identifier')
m = re.fullmatch('[a-k][0369][a-zA-Z0-9#]*',s)
if m!=None:
    print(s, 'is a valid identifier')
else:
    print(s, 'is an invalid identifier')

enter the identifiera9#giuwowyowe
a9#giuwowyowe is a valid identifier


In [213]:
s = input('enter the phone number: ')
m = re.fullmatch('[6-9]\d{9}',s)
if m!=None:
    print(s, 'is a valid phone number')
else:
    print(s, 'is not a valid phone number')

enter the phone number: 975368655
975368655 is not a valid phone number


In [10]:
s = input('enter the phone number: ')
m = re.fullmatch('^[+91]?[0]?[91]?[6-9]\d{9}$',s)
if m!=None:
    print(s, 'is a valid phone number')
else:
    print(s, 'is not a valid phone number')

enter the phone number: +919743030555
+919743030555 is not a valid phone number


In [ ]:
#Regular expressions
#exception handling
#file handling
#oops

In [4]:
import re
s = input('Enter the email address: ')
m = re.fullmatch(('[a-zA-Z0-9_.]*@(gmail|yahoo)[.]com'),s)
if m!=None:
    print("Valid email address")
else:
    print('Invalid email address')

Enter the email address: gsindhu455@stargardens.com
Invalid email address


In [6]:
import re
s = input('Enter the email address: ')
m = re.fullmatch(('[a-zA-Z0-9_.]*@[a-zA-Z0-9]*[.]com'),s)
if m!=None:
    print("Valid email address")
else:
    print('Invalid email address')

Enter the email address: sindhu@tv9.com
Valid email address


In [39]:
import urllib.request
url = 'https://www.summet.com/dmsi/html/codesamples/addresses.html'
response = urllib.request.urlopen(url)
response

In [40]:
data = response.read()
data_str = data.decode()

In [41]:
data_str
pdata = re.findall('\(\d{3}\) \d{3}-\d{4}', data_str)
for i in pdata:
    print(i)

(257) 563-7401
(372) 587-2335
(786) 713-8616
(793) 151-6230
(492) 709-6392
(654) 393-5734
(404) 960-3807
(314) 244-6306
(947) 278-5929
(684) 579-1879
(389) 737-2852
(660) 663-4518
(608) 265-2215
(959) 119-8364
(468) 353-2641
(248) 675-4007
(939) 353-1107
(570) 873-7090
(302) 259-2375
(717) 450-4729
(453) 391-4650
(559) 104-5475
(387) 142-9434
(516) 745-4496
(326) 677-3419
(746) 679-2470
(455) 430-0989
(490) 936-4694
(985) 834-8285
(662) 661-1446
(802) 668-8240
(477) 768-9247
(791) 239-9057
(832) 109-0213
(837) 196-3274
(268) 442-2428
(850) 676-5117
(861) 546-5032
(176) 805-4108
(715) 912-6931
(993) 554-0563
(357) 616-5411
(121) 347-0086
(304) 506-6314
(425) 288-2332
(145) 987-4962
(187) 582-9707
(750) 558-3965
(492) 467-3131
(774) 914-2510
(888) 106-8550
(539) 567-3573
(693) 337-2849
(545) 604-9386
(221) 156-5026
(414) 876-0865
(932) 726-8645
(726) 710-9826
(622) 594-1662
(948) 600-8503
(605) 900-7508
(716) 977-5775
(368) 239-8275
(725) 342-0650
(711) 993-5187
(882) 399-5084
(287) 755-

In [121]:
import time
sites = ['https://www.google.com/','https://www.rediff.com/']
for s in sites:
    print('searching in ......', s)
    time.sleep(5)
    u = urllib.request.urlopen(s)
    text = u.read()
    title = re.findall('<title>.*</title>', str(text), re.IGNORECASE)
    print(title[0])
    time.sleep(5) 
                       

searching in ...... https://www.google.com/
<title>Google</title>
searching in ...... https://www.rediff.com/
<title>Rediff.com: News | Rediffmail | Stock Quotes | Shopping</title>


In [49]:
#exception handling
print('hello')
try:
    print(10/0)
except:
    print('there is and error')
print('hi')

hello
1.0
hi


In [57]:
try:
    result = 0
    x = int(input('enter the number: '))
    y = int(input('enter the number: '))
    result = x/y
except Exception as e:
    print('there is an error')
    print(e)
else:
    print('things are fine')
finally:
    print(result)
#ZeroDivisionError
#TypeError

enter the number: 10
enter the number: 5
things are fine
2.0


In [58]:
try:
    print('statement1')
    print('statement2')
    print('statement3')
    try:
        print('statement4')
        print('statement5')
        print('statement6')
    except:
        print('statement7')
    finally:
        print('statement8')
    print('statement9')
    print()
except:
    print('statement10')
finally:
    print('statement11')
print('statement12')

statement1
statement2
statement3
statement4
statement5
statement6
statement8
statement9

statement11
statement12


In [59]:
try:
    result = 0
    x = int(input('enter the number: '))
    y = int(input('enter the number: '))
    result = x/y
except ZeroDivisionError as e:
    print('there is an error')
    print(e)
except TypeError as e:
    print(e)
else:
    print('things are fine')
finally:
    print(result)
#ZeroDivisionError
#TypeError

enter the number: 10
enter the number: 0
there is an error
division by zero
0


In [66]:
class TooYoungException(Exception):
    """Raise when the age is less than 18"""
    pass

class TooOldException(Exception):
    """Raise when the age is more than 60"""
    pass

In [75]:
try:
    enter_age = int(input('Enter your age: '))
    if enter_age<18:
        raise TooYoungException
    elif enter_age>60:
        raise TooOldException
    else:
        print('Your ticket is confirmed')
        
except TooYoungException:
    print('your age is too less to watch the movie')
    print()
    
except TooOldException:
    print('your age is too high to watch the movie')
    print()
    
else:
    print('Enjoy the movie')
    
finally:
    print('your transaction is completed,Have a nice day!!!')


Enter your age: 12
your age is too less to watch the movie

your transaction is completed,Have a nice day!!!


In [ ]:
#file handling
#Text files
#Binary (Videos,Pictures)
#7 types
# for Text:r,w,a,r+,w+,a+,x
# for Text:rb,wb,ab,r+b,w+b,a+b,xb

In [109]:
import os
os.getcwd()#to get the location of the directory
os.chdir('/Volumes/Personal/Python and AI and ML')# to change the working directory

In [110]:
f = open('edureka2702.txt','w')
print('filename: ',f.name)
print('file mode: ',f.mode)
print('file readable:? ',f.readable())
print('file writable:? ',f.writable())
print('file closed:? ',f.closed)
f.close()
print('file closed:? ',f.closed)

filename:  edureka2702.txt
file mode:  w
file readable:?  False
file writable:?  True
file closed:?  False
file closed:?  True


In [111]:
f = open('edureka2702.txt','w')
f.write('Python looks like an easy programming language\n')
f.write('Earlier i was sacred of Python\n')
f.close()

In [113]:
f = open('edureka2702.txt','w')
f.write('We are looking to become an expert in python\n')
f.write('The reason been is the future\n')
f.close()

In [ ]:
f = open('edureka2702.txt','w')
list1 = ['python is easy','python is basic requirement for AI','']
f.writelines(list1)
f.close()

In [88]:
f = open('edureka2702.txt','r')
data = f.read()#(30 letters)
print(data)
f.close()

Python looks like an easy programming language
Earlier i was sacred of Python



In [122]:
with open('edureka2702.txt','w') as f:
    f.write('I am trying to learn python\n')
    f.write('I want to be a good DS\n')
    print('file closed: ?',f.closed)
print('file closed: ?',f.closed)
#file will be automatically closed once it is out of the with class)

file closed: ? False
file closed: ? True


In [142]:
data = 'learning python is very difficult\nPython is an amazing programming language session\nI would like to learn python at any cost'
f = open('edureka2702.txt','w')
f.write(data)
f.close()

In [143]:
with open('edureka2702.txt','r+')as f:
    text = f.read()
    print(text)
    print(f.tell())#cursor position
    f.seek(24)# go to the position
    print(f.tell())
    f.write('Easy!!!!!')#overwrites
    f.seek(0)
    text = f.read()
    print(text)

learning python is very difficult
Python is an amazing programming language session
I would like to learn python at any cost
124
24
learning python is very Easy!!!!!
Python is an amazing programming language session
I would like to learn python at any cost


In [104]:
#oops
def ctof(c):
    f = (c*9/5)+32
    return f
ctof(10)

50.0

In [107]:
class celtofer:
    def __init__(self,c):
        self.c = c
    
    def ctof(self):
        f =(self.c*9/5)+32
        print(f)
c1 = celtofer(10)
c1.ctof()

50.0


In [205]:
with open('mynewfile.txt','w')as f:
    data ='Lead the scene and keep it green.\nKeep green and keep our planet clean.\nTake a stand for the love of green.\nDont be mean,just go green.\nThink green.\n'
    f.writelines(data)
f = open('mynewfile.txt','r')
text = f.read()
print(text)
s = f.readlines()
print(f.tell())

Lead the scene and keep it green.
Keep green and keep our planet clean.
Take a stand for the love of green.
Dont be mean,just go green.
Think green.

155


In [191]:
file = open("mynewfile.txt","r")
data = file.read()
no_of_characters = len(data)
print('number of characters: ',no_of_characters )

number of characters:  149


In [274]:
import os
import sys
fname = input('enter the filenme: ')
if os.path.isfile(fname):
    print('file exists: ',fname)
    f = open(fname, 'r')
else:
    print('file doesnt exists')
    sys.exit(0)
lcount=wcount=ccount=0
for line in f:
    lcount = lcount + 1
    ccount =ccount + len(line)
    words = line.split()
    wcount = wcount + len(words)

print('The number of Lines: ',lcount)
print('The number of words: ',wcount)
print('The number of characters: ',ccount)
    

enter the filenme: mynewfile.txt
file exists:  mynewfile.txt
The number of Lines:  5
The number of words:  29
The number of characters:  149


In [189]:
class celtofer:
    def __init__(self,c):
        self.c = c
    
    def ctof(self):
        f =(self.c*9/5)+32
        print(f)
c1 = celtofer(10)
c1.ctof()
c2 = celtofer(20)
c2.ctof()
#self is memory location of individual objects

50.0
68.0


In [203]:
class Society:
    def __init__(self, name, address, age, salary):
        self.n = name
        self.addr = address
        self.age = age
        self.sal = salary
    def display(self):
        print('Hey guys my name is: ',self.n,'My address is: ',self.addr,'my age is: ',self.age)
        print('My salary is : ', self.sal)

res1 = Society('A', 606, 35, 10000)
res1.display()
res2 = Society('B', 607, 32, 12000)
res2.display()

Hey guys my name is:  A My address is:  606 my age is:  35
My salary is :  10000
Hey guys my name is:  B My address is:  607 my age is:  32
My salary is :  12000


In [210]:
class Loan:
    #Static Variables
    Bankname = 'Edureka Bank'
    interestrate = 0.10
    def __init__(self, name, age, salary):
        self.n = name
        self.a = age
        self.s = salary
        
    def interestcalci(self):
        print('Welcome to the: ',Loan.Bankname, 'you are eligible for ',self.s*Loan.interestrate, 'amount of loan')
        print('Your Location is : ',Loan.location)
    # static variables
    location = 'Bangalore'
    
    def agecriteria(self):
        if self.a>30:
            print('you will not get the loan')
        else:
            print('you will get a loan')
        
#object = instance Variables    
cust1 = Loan('Rahul',35,10000)
cust1.interestcalci()
cust1.agecriteria()

cust2 = Loan('Sindhu',23,9000)
cust2.interestcalci()
cust2.agecriteria()

cust3 = Loan('Sindhu',25,8000)
cust3.interestcalci()
cust3.agecriteria()       

Welcome to the:  Edureka Bank you are eligible for  1000.0 amount of loan
Your Location is :  Bangalore
you will not get the loan
Welcome to the:  Edureka Bank you are eligible for  900.0 amount of loan
Your Location is :  Bangalore
you will get a loan
Welcome to the:  Edureka Bank you are eligible for  800.0 amount of loan
Your Location is :  Bangalore
you will get a loan


In [232]:
class Test:
    def __init__(self):
        self.a = 10
    def m1(self):
        self.a = 777
        self.b = 888
        
t1 = Test()
print(t1.__dict__)  
t1.m1()
print(t1.__dict__)
t1.c = 999
print(t1.__dict__)
    

{'a': 10}
{'a': 777, 'b': 888}
{'a': 777, 'b': 888, 'c': 999}


In [235]:
class Test:
    a=10
    def __init__(self):
        #Local Variables
        self.c = 100
        Test.y = 500
    def m1(self):
        self.a = 777
        self.b = 888
        
t1 = Test()
print(t1.__dict__)  
print(Test.__dict__)
t1.m1()
print(t1.__dict__)
Test.z = 1000
print(Test.__dict__)
t1.a
Test.a


{'c': 100}
{'__module__': '__main__', 'a': 10, '__init__': <function Test.__init__ at 0x7fbeede6e550>, 'm1': <function Test.m1 at 0x7fbeede6ee50>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None, 'y': 500}
{'c': 100, 'a': 777, 'b': 888}
{'__module__': '__main__', 'a': 10, '__init__': <function Test.__init__ at 0x7fbeede6e550>, 'm1': <function Test.m1 at 0x7fbeede6ee50>, '__dict__': <attribute '__dict__' of 'Test' objects>, '__weakref__': <attribute '__weakref__' of 'Test' objects>, '__doc__': None, 'y': 500, 'z': 1000}


10

In [231]:
class Employee:
    def __init__(self,eno,ename,esal):
        self.eno = eno
        self.ename = ename
        self.esal = esal
    
    def display(self):
        print('My name is: ', self.ename)
        print('My eno is: ', self.eno)
        print('My Salary is: ', self.esal)
        
e = Employee(10,'Rahul',10000)
e.display()

class Test:
    def modify(emp):
        emp.esal = emp.esal+10000
        emp.display()
        
Test.modify(e)

My name is:  Rahul
My eno is:  10
My Salary is:  10000
My name is:  Rahul
My eno is:  10
My Salary is:  20000


In [237]:
#Inheritence
#Single Inheritenc: one parent to one child class
#properties of class P(parent) is transfered to class C(child)
class P:
    def m1(self):
        print('Parent class method')
class C(P):# inside the braces is parent
    def m2(self):
        print('child Class method')
p1 = P()
p1.m1()
#p1.m2 doesnt work as P is parent
#(properties of P is inherited to C(m1 but not m2))
c1 = C()
c1.m2()
c1.m1()

Parent class method
child Class method
Parent class method


In [238]:
#Multi level inheritence
#multi level Inheritenc: one parent to one child class and one child child class
#properties of class P(parent) is transfered to class C(child)
class P:
    def m1(self):
        print('Parent class method')
class C(P):# inside the braces is parent
    def m2(self):
        print('child Class method')
class CC(C):
    def m3(self):
        print('Sub child method')
        
p1 = P()
p1.m1()
#p1.m2 doesnt work as P is parent
#(properties of P is inherited to C(m1 but not m2))
c1 = C()
c1.m2()
c1.m1()
#Properties of both P and C is inheritted to CC sub child class
cc1 = CC()
cc1.m1()
cc1.m2()
cc1.m3()

Parent class method
child Class method
Parent class method
Parent class method
child Class method
Sub child method


In [240]:
#hierarchiel inheritence
#hierarchiel Inheritenc: one parent to two child class 
#properties of class P(parent) is transfered to class C(child)
class P:
    def m1(self):
        print('Parent class method')
class C1(P):
    def m2(self):
        print('child 1 Class method')
class C2(P):
    def m3(self):
        print('child 2 child method')
        
p1 = P()
p1.m1()

c1 = C1()
c1.m2()
c1.m1()
#P properties will be inherited to c1 and C2
#but C1 properties will not be inherited to C1
c2 = C2()
c2.m1()
c2.m3()

Parent class method
child 1 Class method
Parent class method
Parent class method
child 2 child method


In [242]:
#multiple inheritence
#single parent and 2 child classes
class P1:
    def m1(self):
        print('Parent 1 class method')
class P2:
    def m2(self):
        print('Parent 2 Class method')
class C(P1,P2):
    def m3(self):
        print('Multiple method')
        
c1 = C()
c1.m1()
c1.m2()
c1.m3()
# C will get the properties of both P1 and P2

Parent 1 class method
Parent 2 Class method
Multiple method


In [248]:
class A:
    def m1(self):
        print('A class method...')
class B(A):
    def m1(self):
        print('B class method...')
class C(B):
    def m2(self):
        print('C class method...')
class D(C):
    def m1(self):
        print('D class method...')
class E(D):
    def m1(self):
        print('E class method...')
        super().m1()
        B.m1(self)
        super(B,self).m1()
        super(D,self).m2()
e = E()
e.m1()

E class method...
D class method...
B class method...
A class method...
C class method...


In [250]:
#polymorphism
  #many forms
a= 10
b= 20
a+b

30

In [249]:
a= '10'
b= '20'
a+b

'1020'

In [251]:
#magic methods
dir(int)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [260]:
class Book:
    def __init__(self,pages):
        self.pages = pages
    def __add__(self,other):
        total = self.pages + other.pages
        return Book(total)
    def __str__(self):
        return str(self.pages)
    
b1 = Book(100)
b2 = Book(200)
b3 = Book(300)
b4 = Book(250)
print(b1+b2+b3+b4)

850


In [261]:
Employee(1,'A',10)

In [266]:
class Test:
    def m1(self,a1,b1):
        print('a')
    def m1(self,a1):
        print('b')
    def m1(self):
        print('c')
t = Test()
t.m1()     

c


In [275]:
class P:
    def property(self):
        print('car,house,gold,cash')
        
    def marriage(self):
        print('x')
class C(P):
    def marriage(self):
        super().marriage()
        print('a')
c = C()
c.marriage()
c.property()
        

x
a
car,house,gold,cash


In [271]:
#which will add any number of numbers
class Calc:
    def sum(self,*a):
        total = 0
        for x in a:
            total = total+x
        print('the sum is: ',total)
c = Calc()
c.sum(1,2,3,4,5,6,7,8,9,5,6,1)

the sum is:  57


In [ ]:
text = input('enter the string to be reversed')


In [3]:
import numpy as np
np.version.version

'1.19.2'

In [4]:
sales = [4344,3333,4343,4433,2222]
profit = [432,222,323,322,222]
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio
    

[0.09944751381215469,
 0.0666066606660666,
 0.07437255353442321,
 0.07263704037897586,
 0.0999099909990999]

In [8]:
import numpy as np
sales_array = np.array(sales)

In [9]:
profit_array = np.array(profit)

In [10]:
type(sales_array)

numpy.ndarray

In [11]:
profit_array/sales_array

array([0.09944751, 0.06660666, 0.07437255, 0.07263704, 0.09990999])

In [12]:
import time
size = 1000000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)

start =time.time()
result = [(x,y) for x,y in zip(l1,l2)]
print('time taken by list operation')
print((time.time()-start)*1000)

start =time.time()
result = a1+a2
print('time taken by array')
print((time.time()-start)*1000)


time taken by list operation
212.2781276702881
time taken by array
45.90606689453125


In [14]:
list1=['a',10,12.5,True]


In [15]:
#all the different data types in list will be converted to one single datatype
#the first value in the dataset will be taking the priority
a=np.array(list1)
type(a[0])

numpy.str_

In [17]:
list2=[10,12.5,True]
a=np.array(list2)
type(a[0])

numpy.float64

In [20]:
sales*3 #it multiplies the  whole list

[4344,
 3333,
 4343,
 4433,
 2222,
 4344,
 3333,
 4343,
 4433,
 2222,
 4344,
 3333,
 4343,
 4433,
 2222]

In [21]:
sales_array*2#it multiplies each value

array([8688, 6666, 8686, 8866, 4444])

In [42]:
sales_eu =[2342,2432,3434,4343]
sales_us =[2233,4344,3422,2222]
sales_jp =[2323,4343,4444,3333]
a=np.array([sales_eu,sales_us,sales_jp])
a

array([[2342, 2432, 3434, 4343],
       [2233, 4344, 3422, 2222],
       [2323, 4343, 4444, 3333]])

In [43]:
a[1:3,2:4]

array([[3422, 2222],
       [4444, 3333]])

In [44]:
a[1:3,1:4]

array([[4344, 3422, 2222],
       [4343, 4444, 3333]])

In [45]:
#left rows and right is columns and it takes only two arguments
a[0:2,1:3]

array([[2432, 3434],
       [4344, 3422]])

In [46]:
a[0:3]

array([[2342, 2432, 3434, 4343],
       [2233, 4344, 3422, 2222],
       [2323, 4343, 4444, 3333]])

In [47]:
a[:,0:1]
#is a 3cross1 matrix

array([[2342],
       [2233],
       [2323]])

In [48]:
a
#is a 4cross4 array

array([[2342, 2432, 3434, 4343],
       [2233, 4344, 3422, 2222],
       [2323, 4343, 4444, 3333]])

In [49]:
profit_eu = [432,222,323,322]
profit_us =[232,343,432,324]
profit_jp = [343,342,333,242]
b=np.array([profit_eu,profit_us,profit_jp])
b

array([[432, 222, 323, 322],
       [232, 343, 432, 324],
       [343, 342, 333, 242]])

In [50]:
b/a

array([[0.18445773, 0.09128289, 0.09405941, 0.0741423 ],
       [0.1038961 , 0.07895948, 0.12624196, 0.14581458],
       [0.1476539 , 0.07874741, 0.07493249, 0.07260726]])

In [58]:
a.min()

2222

In [56]:
a.max()

4444

In [59]:
np.max(a,axis=0)#for column wise wise which is maximum value

array([2342, 4344, 4444, 4343])

In [60]:
np.max(a,axis=1)#for row wise

array([4343, 4344, 4444])

In [61]:
np.mean(a,axis=0)

array([2299.33333333, 3706.33333333, 3766.66666667, 3299.33333333])

In [62]:
np.median(a,axis=1)

array([2933. , 2827.5, 3838. ])

In [63]:
a

array([[2342, 2432, 3434, 4343],
       [2233, 4344, 3422, 2222],
       [2323, 4343, 4444, 3333]])

In [65]:
a[np.where(a>4000)]

array([4343, 4344, 4343, 4444])

In [66]:
np.sqrt(a)#squareroot 

array([[48.39421453, 49.31531202, 58.6003413 , 65.90144156],
       [47.2546294 , 65.90902821, 58.49786321, 47.138095  ],
       [48.19751031, 65.90144156, 66.66333325, 57.7321401 ]])

In [68]:
np.sqrt(100)

10.0

In [72]:
np.sqrt(a.max(axis=0))#squareroot(maximum value of the each column)

array([48.39421453, 65.90902821, 66.66333325, 65.90144156])

In [112]:
stu_dtls ={'sid':[1,2,3,4,5],
         'sname':['a','b','c','d','e'],
         'sregion':['s','w','e','n','s']}

In [113]:
stu_dtls

{'sid': [1, 2, 3, 4, 5],
 'sname': ['a', 'b', 'c', 'd', 'e'],
 'sregion': ['s', 'w', 'e', 'n', 's']}

In [114]:
stu_mrks ={'sid':[1,2,3,4,6],
          'smarks':[21,22,24,26,28],
          'sub':['py','r','tab','py','py']}

In [96]:
a=pd.DataFrame(stu_dtls)
type(a)
b=pd.DataFrame(stu_mrks)
type(b)

pandas.core.frame.DataFrame

In [94]:
a

sid sname sregion
0    1     a       s
1    2     b       w
2    3     c       e
3    4     d       n
4    5     e       s

In [97]:
b

sid  smarks  sub
0    1      21   py
1    2      22    r
2    3      24  tab
3    4      26   py
4    6      28   py

In [98]:
pd.merge(a,b)

sid sname sregion  smarks  sub
0    1     a       s      21   py
1    2     b       w      22    r
2    3     c       e      24  tab
3    4     d       n      26   py

In [99]:
pd.merge(a,b,how='left')

sid sname sregion  smarks  sub
0    1     a       s    21.0   py
1    2     b       w    22.0    r
2    3     c       e    24.0  tab
3    4     d       n    26.0   py
4    5     e       s     NaN  NaN

In [100]:
pd.merge(a,b,how='right')

sid sname sregion  smarks  sub
0    1     a       s      21   py
1    2     b       w      22    r
2    3     c       e      24  tab
3    4     d       n      26   py
4    6   NaN     NaN      28   py

In [101]:
pd.merge(a,b,how='outer')

sid sname sregion  smarks  sub
0    1     a       s    21.0   py
1    2     b       w    22.0    r
2    3     c       e    24.0  tab
3    4     d       n    26.0   py
4    5     e       s     NaN  NaN
5    6   NaN     NaN    28.0   py

In [116]:
pd.merge(a,b,how='outer',left_on='sid',right_on='sid')
#if 2 columns should be joined the add the column name to the list

sid sname sregion  smarks  sub
0    1     a       s    21.0   py
1    2     b       w    22.0    r
2    3     c       e    24.0  tab
3    4     d       n    26.0   py
4    5     e       s     NaN  NaN
5    6   NaN     NaN    28.0   py

In [121]:
dtls ={'sid':[1,2,3,4,5],
         'sname':['a','b','c','d','e'],
         'sregion':['s','w','e','n','s']}
a=pd.DataFrame(dtls)
a

sid sname sregion
0    1     a       s
1    2     b       w
2    3     c       e
3    4     d       n
4    5     e       s

In [122]:
mrks ={'bel':[1,2,3,4,6],
          'smarks':[21,22,24,26,28],
          'sub':['py','r','tab','py','py']}
b=pd.DataFrame(mrks)
b

bel  smarks  sub
0    1      21   py
1    2      22    r
2    3      24  tab
3    4      26   py
4    6      28   py

In [123]:
pd.merge(a,b,how='outer',left_on='sid',right_on='bel')

sid sname sregion  bel  smarks  sub
0  1.0     a       s  1.0    21.0   py
1  2.0     b       w  2.0    22.0    r
2  3.0     c       e  3.0    24.0  tab
3  4.0     d       n  4.0    26.0   py
4  5.0     e       s  NaN     NaN  NaN
5  NaN   NaN     NaN  6.0    28.0   py

In [177]:
import os
os.chdir('/Volumes/Personal/Python and AI and ML')

In [178]:
os.getcwd()

'/Volumes/Personal/Python and AI and ML'

In [179]:
tips = pd.read_csv('tips.csv')
type(tips)
len(tips)#no.rows
len(tips.columns)#no.column
tips.head(2)#2 records from header
tips.info()#details
tips.describe()#details on count ,calculations

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [180]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [183]:
tips.rename(columns={'total_bill':'totalbill','sex':'gender','size':'totalcust'} ,inplace = True)
# OR we can assign it to tips 


In [185]:
tips

totalbill   tip  gender smoker   day    time  totalcust
0        16.99  1.01  Female     No   Sun  Dinner          2
1        10.34  1.66    Male     No   Sun  Dinner          3
2        21.01  3.50    Male     No   Sun  Dinner          3
3        23.68  3.31    Male     No   Sun  Dinner          2
4        24.59  3.61  Female     No   Sun  Dinner          4
..         ...   ...     ...    ...   ...     ...        ...
239      29.03  5.92    Male     No   Sat  Dinner          3
240      27.18  2.00  Female    Yes   Sat  Dinner          2
241      22.67  2.00    Male    Yes   Sat  Dinner          2
242      17.82  1.75    Male     No   Sat  Dinner          2
243      18.78  3.00  Female     No  Thur  Dinner          2

[244 rows x 7 columns]

In [186]:
tips[['totalbill','tip','day']]#only get relavant or required data 

totalbill   tip   day
0        16.99  1.01   Sun
1        10.34  1.66   Sun
2        21.01  3.50   Sun
3        23.68  3.31   Sun
4        24.59  3.61   Sun
..         ...   ...   ...
239      29.03  5.92   Sat
240      27.18  2.00   Sat
241      22.67  2.00   Sat
242      17.82  1.75   Sat
243      18.78  3.00  Thur

[244 rows x 3 columns]

In [187]:
tips.iloc[:,:]#first is rows,second is columns

totalbill   tip  gender smoker   day    time  totalcust
0        16.99  1.01  Female     No   Sun  Dinner          2
1        10.34  1.66    Male     No   Sun  Dinner          3
2        21.01  3.50    Male     No   Sun  Dinner          3
3        23.68  3.31    Male     No   Sun  Dinner          2
4        24.59  3.61  Female     No   Sun  Dinner          4
..         ...   ...     ...    ...   ...     ...        ...
239      29.03  5.92    Male     No   Sat  Dinner          3
240      27.18  2.00  Female    Yes   Sat  Dinner          2
241      22.67  2.00    Male    Yes   Sat  Dinner          2
242      17.82  1.75    Male     No   Sat  Dinner          2
243      18.78  3.00  Female     No  Thur  Dinner          2

[244 rows x 7 columns]

In [188]:
tips.iloc[0:4,:]
tips.iloc[:,[0,3,6]]#for relevant columns
tips.iloc[0:4,:].values#lists only values 

array([[16.99, 1.01, 'Female', 'No', 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', 'No', 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', 'No', 'Sun', 'Dinner', 3],
       [23.68, 3.31, 'Male', 'No', 'Sun', 'Dinner', 2]], dtype=object)

In [189]:
tips[tips['time']=='Dinner']

totalbill   tip  gender smoker   day    time  totalcust
0        16.99  1.01  Female     No   Sun  Dinner          2
1        10.34  1.66    Male     No   Sun  Dinner          3
2        21.01  3.50    Male     No   Sun  Dinner          3
3        23.68  3.31    Male     No   Sun  Dinner          2
4        24.59  3.61  Female     No   Sun  Dinner          4
..         ...   ...     ...    ...   ...     ...        ...
239      29.03  5.92    Male     No   Sat  Dinner          3
240      27.18  2.00  Female    Yes   Sat  Dinner          2
241      22.67  2.00    Male    Yes   Sat  Dinner          2
242      17.82  1.75    Male     No   Sat  Dinner          2
243      18.78  3.00  Female     No  Thur  Dinner          2

[176 rows x 7 columns]

In [190]:
tips[(tips['time']=='Dinner')&(tips['tip']>5)]#and (time = Dinner and tip>5 )

totalbill    tip  gender smoker  day    time  totalcust
23       39.42   7.58    Male     No  Sat  Dinner          4
44       30.40   5.60    Male     No  Sun  Dinner          4
47       32.40   6.00    Male     No  Sun  Dinner          4
52       34.81   5.20  Female     No  Sun  Dinner          4
59       48.27   6.73    Male     No  Sat  Dinner          4
116      29.93   5.07    Male     No  Sun  Dinner          4
155      29.85   5.14  Female     No  Sun  Dinner          5
170      50.81  10.00    Male    Yes  Sat  Dinner          3
172       7.25   5.15    Male    Yes  Sun  Dinner          2
181      23.33   5.65    Male    Yes  Sun  Dinner          2
183      23.17   6.50    Male    Yes  Sun  Dinner          4
211      25.89   5.16    Male    Yes  Sat  Dinner          4
212      48.33   9.00    Male     No  Sat  Dinner          4
214      28.17   6.50  Female    Yes  Sat  Dinner          3
239      29.03   5.92    Male     No  Sat  Dinner          3

In [191]:
tips[(tips['time']=='Dinner')|(tips['tip']>5)] #or

totalbill   tip  gender smoker   day    time  totalcust
0        16.99  1.01  Female     No   Sun  Dinner          2
1        10.34  1.66    Male     No   Sun  Dinner          3
2        21.01  3.50    Male     No   Sun  Dinner          3
3        23.68  3.31    Male     No   Sun  Dinner          2
4        24.59  3.61  Female     No   Sun  Dinner          4
..         ...   ...     ...    ...   ...     ...        ...
239      29.03  5.92    Male     No   Sat  Dinner          3
240      27.18  2.00  Female    Yes   Sat  Dinner          2
241      22.67  2.00    Male    Yes   Sat  Dinner          2
242      17.82  1.75    Male     No   Sat  Dinner          2
243      18.78  3.00  Female     No  Thur  Dinner          2

[179 rows x 7 columns]

In [194]:
tips

totalbill   tip  gender smoker   day    time  totalcust
0        16.99  1.01  Female     No   Sun  Dinner          2
1        10.34  1.66    Male     No   Sun  Dinner          3
2        21.01  3.50    Male     No   Sun  Dinner          3
3        23.68  3.31    Male     No   Sun  Dinner          2
4        24.59  3.61  Female     No   Sun  Dinner          4
..         ...   ...     ...    ...   ...     ...        ...
239      29.03  5.92    Male     No   Sat  Dinner          3
240      27.18  2.00  Female    Yes   Sat  Dinner          2
241      22.67  2.00    Male    Yes   Sat  Dinner          2
242      17.82  1.75    Male     No   Sat  Dinner          2
243      18.78  3.00  Female     No  Thur  Dinner          2

[244 rows x 7 columns]

In [196]:
tips[(tips['day']=='Thur')|(tips['day']=='Fri')|(tips['day']=='Sat')]

totalbill   tip  gender smoker   day    time  totalcust
19       20.65  3.35    Male     No   Sat  Dinner          3
20       17.92  4.08    Male     No   Sat  Dinner          2
21       20.29  2.75  Female     No   Sat  Dinner          2
22       15.77  2.23  Female     No   Sat  Dinner          2
23       39.42  7.58    Male     No   Sat  Dinner          4
..         ...   ...     ...    ...   ...     ...        ...
239      29.03  5.92    Male     No   Sat  Dinner          3
240      27.18  2.00  Female    Yes   Sat  Dinner          2
241      22.67  2.00    Male    Yes   Sat  Dinner          2
242      17.82  1.75    Male     No   Sat  Dinner          2
243      18.78  3.00  Female     No  Thur  Dinner          2

[168 rows x 7 columns]

In [197]:
tips.day.unique()#to know how many unique values for day column

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [198]:
tips[tips['day'].isin(['Thur','Fri','Sat'])]#in single

totalbill   tip  gender smoker   day    time  totalcust
19       20.65  3.35    Male     No   Sat  Dinner          3
20       17.92  4.08    Male     No   Sat  Dinner          2
21       20.29  2.75  Female     No   Sat  Dinner          2
22       15.77  2.23  Female     No   Sat  Dinner          2
23       39.42  7.58    Male     No   Sat  Dinner          4
..         ...   ...     ...    ...   ...     ...        ...
239      29.03  5.92    Male     No   Sat  Dinner          3
240      27.18  2.00  Female    Yes   Sat  Dinner          2
241      22.67  2.00    Male    Yes   Sat  Dinner          2
242      17.82  1.75    Male     No   Sat  Dinner          2
243      18.78  3.00  Female     No  Thur  Dinner          2

[168 rows x 7 columns]

In [199]:
tips.isnull().sum()#to check if any null values

totalbill    0
tip          0
gender       0
smoker       0
day          0
time         0
totalcust    0
dtype: int64

In [200]:
tips.groupby('gender').count()#group by the header required
#or
tips.groupby('gender').size()

gender
Female     87
Male      157
dtype: int64

In [201]:
# group by multiple columns
tips.groupby(['gender','smoker']).size()

gender  smoker
Female  No        54
        Yes       33
Male    No        97
        Yes       60
dtype: int64

In [205]:
tips.groupby(['day','gender','smoker']).agg({'tip':np.mean})

tip
day  gender smoker          
Fri  Female No      3.125000
            Yes     2.682857
     Male   No      2.500000
            Yes     2.741250
Sat  Female No      2.724615
            Yes     2.868667
     Male   No      3.256563
            Yes     2.879259
Sun  Female No      3.329286
            Yes     3.500000
     Male   No      3.115349
            Yes     3.521333
Thur Female No      2.459600
            Yes     2.990000
     Male   No      2.941500
            Yes     3.058000

In [155]:
df = pd.DataFrame({'Name':['Narendra Pratap singh','Arun Kumar Mishra','Yogendra Nath Reddy'],
                'location':['Bhopal MP','Lucknow UP','Kolkatta WB']})

In [156]:
name = df.Name.str.split(' ',expand=True)
name

0       1       2
0  Narendra  Pratap   singh
1      Arun   Kumar  Mishra
2  Yogendra    Nath   Reddy

In [157]:
df[['first_name','middle_name','last_name']]=df.Name.str.split(' ',expand=True)
df

Name     location first_name middle_name last_name
0  Narendra Pratap singh    Bhopal MP   Narendra      Pratap     singh
1      Arun Kumar Mishra   Lucknow UP       Arun       Kumar    Mishra
2    Yogendra Nath Reddy  Kolkatta WB   Yogendra        Nath     Reddy

In [147]:
df[['City','State']]=df.location.str.split(' ',expand=True)
df

location first_name middle_name last_name      City State
0    Bhopal MP   Narendra      Pratap     singh    Bhopal    MP
1   Lucknow UP       Arun       Kumar    Mishra   Lucknow    UP
2  Kolkatta WB   Yogendra        Nath     Reddy  Kolkatta    WB

In [159]:
df.drop('Name',axis=1,inplace=True)
df

first_name middle_name last_name
0   Narendra      Pratap     singh
1       Arun       Kumar    Mishra
2   Yogendra        Nath     Reddy

In [206]:
tips

totalbill   tip  gender smoker   day    time  totalcust
0        16.99  1.01  Female     No   Sun  Dinner          2
1        10.34  1.66    Male     No   Sun  Dinner          3
2        21.01  3.50    Male     No   Sun  Dinner          3
3        23.68  3.31    Male     No   Sun  Dinner          2
4        24.59  3.61  Female     No   Sun  Dinner          4
..         ...   ...     ...    ...   ...     ...        ...
239      29.03  5.92    Male     No   Sat  Dinner          3
240      27.18  2.00  Female    Yes   Sat  Dinner          2
241      22.67  2.00    Male    Yes   Sat  Dinner          2
242      17.82  1.75    Male     No   Sat  Dinner          2
243      18.78  3.00  Female     No  Thur  Dinner          2

[244 rows x 7 columns]

In [207]:
tips.select_dtypes(exclude=['float64','int64'])#excludes float and int

gender smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [208]:
tips.groupby('gender').agg({'totalbill':np.sum})

totalbill
gender           
Female    1570.95
Male      3256.82

In [210]:
totalsales = tips.groupby('gender').totalbill.transform('sum')
totalsales

0      1570.95
1      3256.82
2      3256.82
3      3256.82
4      1570.95
        ...   
239    3256.82
240    1570.95
241    3256.82
242    3256.82
243    1570.95
Name: totalbill, Length: 244, dtype: float64

In [211]:
tips['totalsales']=totalsales

In [212]:
tips

totalbill   tip  gender smoker   day    time  totalcust  totalsales
0        16.99  1.01  Female     No   Sun  Dinner          2     1570.95
1        10.34  1.66    Male     No   Sun  Dinner          3     3256.82
2        21.01  3.50    Male     No   Sun  Dinner          3     3256.82
3        23.68  3.31    Male     No   Sun  Dinner          2     3256.82
4        24.59  3.61  Female     No   Sun  Dinner          4     1570.95
..         ...   ...     ...    ...   ...     ...        ...         ...
239      29.03  5.92    Male     No   Sat  Dinner          3     3256.82
240      27.18  2.00  Female    Yes   Sat  Dinner          2     1570.95
241      22.67  2.00    Male    Yes   Sat  Dinner          2     3256.82
242      17.82  1.75    Male     No   Sat  Dinner          2     3256.82
243      18.78  3.00  Female     No  Thur  Dinner          2     1570.95

[244 rows x 8 columns]

In [214]:
tips['%total']=(tips.totalbill/tips.totalsales)*100
tips

totalbill   tip  gender smoker   day    time  totalcust  totalsales  \
0        16.99  1.01  Female     No   Sun  Dinner          2     1570.95   
1        10.34  1.66    Male     No   Sun  Dinner          3     3256.82   
2        21.01  3.50    Male     No   Sun  Dinner          3     3256.82   
3        23.68  3.31    Male     No   Sun  Dinner          2     3256.82   
4        24.59  3.61  Female     No   Sun  Dinner          4     1570.95   
..         ...   ...     ...    ...   ...     ...        ...         ...   
239      29.03  5.92    Male     No   Sat  Dinner          3     3256.82   
240      27.18  2.00  Female    Yes   Sat  Dinner          2     1570.95   
241      22.67  2.00    Male    Yes   Sat  Dinner          2     3256.82   
242      17.82  1.75    Male     No   Sat  Dinner          2     3256.82   
243      18.78  3.00  Female     No  Thur  Dinner          2     1570.95   

       %total  
0    1.081511  
1    0.317488  
2    0.645108  
3    0.727090  
4    1.565295  
..        ...  
239  0.891360  
240  1.730163  
241  0.696078  
242  0.547159  
243  1.195455  

[244 rows x 9 columns]

In [215]:
tips.groupby(['gender','day']).totalbill.mean().unstack()#or

day           Fri        Sat        Sun       Thur
gender                                            
Female  14.145556  19.680357  19.872222  16.715312
Male    19.857000  20.802542  21.887241  18.714667

In [219]:
#we canuse either unstack or pivot_table
tips.pivot_table(index='gender',columns='day',values='totalbill',aggfunc='mean')
tips

totalbill   tip  gender smoker   day    time  totalcust  totalsales  \
0        16.99  1.01  Female     No   Sun  Dinner          2     1570.95   
1        10.34  1.66    Male     No   Sun  Dinner          3     3256.82   
2        21.01  3.50    Male     No   Sun  Dinner          3     3256.82   
3        23.68  3.31    Male     No   Sun  Dinner          2     3256.82   
4        24.59  3.61  Female     No   Sun  Dinner          4     1570.95   
..         ...   ...     ...    ...   ...     ...        ...         ...   
239      29.03  5.92    Male     No   Sat  Dinner          3     3256.82   
240      27.18  2.00  Female    Yes   Sat  Dinner          2     1570.95   
241      22.67  2.00    Male    Yes   Sat  Dinner          2     3256.82   
242      17.82  1.75    Male     No   Sat  Dinner          2     3256.82   
243      18.78  3.00  Female     No  Thur  Dinner          2     1570.95   

       %total  
0    1.081511  
1    0.317488  
2    0.645108  
3    0.727090  
4    1.565295  
..        ...  
239  0.891360  
240  1.730163  
241  0.696078  
242  0.547159  
243  1.195455  

[244 rows x 9 columns]

In [221]:
tips['runningtotalbill']=tips.totalbill.cumsum()
tips#running total
tips['gensmk']= tips.gender + ':' + tips.smoker
#concatination and creation of new column
tips

totalbill   tip  gender smoker   day    time  totalcust  totalsales  \
0        16.99  1.01  Female     No   Sun  Dinner          2     1570.95   
1        10.34  1.66    Male     No   Sun  Dinner          3     3256.82   
2        21.01  3.50    Male     No   Sun  Dinner          3     3256.82   
3        23.68  3.31    Male     No   Sun  Dinner          2     3256.82   
4        24.59  3.61  Female     No   Sun  Dinner          4     1570.95   
..         ...   ...     ...    ...   ...     ...        ...         ...   
239      29.03  5.92    Male     No   Sat  Dinner          3     3256.82   
240      27.18  2.00  Female    Yes   Sat  Dinner          2     1570.95   
241      22.67  2.00    Male    Yes   Sat  Dinner          2     3256.82   
242      17.82  1.75    Male     No   Sat  Dinner          2     3256.82   
243      18.78  3.00  Female     No  Thur  Dinner          2     1570.95   

       %total  runningtotalbill      gensmk  
0    1.081511             16.99   Female:No  
1    0.317488             27.33     Male:No  
2    0.645108             48.34     Male:No  
3    0.727090             72.02     Male:No  
4    1.565295             96.61   Female:No  
..        ...               ...         ...  
239  0.891360           4741.32     Male:No  
240  1.730163           4768.50  Female:Yes  
241  0.696078           4791.17    Male:Yes  
242  0.547159           4808.99     Male:No  
243  1.195455           4827.77   Female:No  

[244 rows x 11 columns]

In [222]:
df = pd.DataFrame({'Gender':['male','female','male','female','female'],
                  'age':['12','24','38','17','23'],
                  'color':['blue','green','white','black','red']})
df

Gender age  color
0    male  12   blue
1  female  24  green
2    male  38  white
3  female  17  black
4  female  23    red

In [223]:
df['canvote'] = df.age.astype(int)>18
df

Gender age  color  canvote
0    male  12   blue    False
1  female  24  green     True
2    male  38  white     True
3  female  17  black    False
4  female  23    red     True

In [226]:
df['canvote'] = df.canvote.map({True:'yes',False:'no'})
df

Gender age  color canvote
0    male  12   blue      no
1  female  24  green     yes
2    male  38  white     yes
3  female  17  black      no
4  female  23    red     yes